# Generated by Django 3.1 on 2020-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '历次考试科目'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': '成绩'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生名单'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=5, verbose_name='科目'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_gender',
            field=models.CharField(choices=[('MALE', '男'), ('FEMALE', '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(max_length=20, verbose_name='学生姓名'),
        ),
    ]
